package other;

public enum UserInputType {
    PATIENT_NAME,
    PATIENT_SURNAME,
    PATIENT_ID,
    PATIENT_IC,
    PATIENT_BIRTH,
    HOSPITALIZATION_ID,
    DIAGNOSIS,
    HOSPITALIZATION_END,
    HOSPITALIZATION_START,
    DB_QUANTITY_PATIENTS,
    DB_QUANTITY_HOSPITALIZATIONS
}
